name: Linux
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: ['alpine', 'arm64', 'armhf', 'amd64']
    steps:
      - uses: actions/checkout@v4
      - name: Setup tags
        run: |
          set -x
          component=${{ matrix.component }}
          for target in $(make echo-all-images); do
            case $target in
               *$component*)
                 ;;
               *)
                 continue
                 ;;
            esac
            branch=$(echo $target | cut -d'/' -f1)
            tags=$(echo $target | cut -d':' -f2-)
            edited_tags=""
            for tag in $(echo $tags | tr , ' '); do
              if [ -z $edited_tags ]; then
                edited_tags="repo:$tag"
              else
                edited_tags+=",repo:$tag"
              fi
            done
            case $component in
            *alpine*)
              echo "CONTEXT=${branch}/${component}"
              echo "ALPINETAGS=$edited_tags"
              ;;
            *arm64*)
              echo "CONTEXT=${branch}/${component}/debian"
              echo "ARM64TAGS=$edited_tags"
              ;;
            *armhf*)
              echo "CONTEXT=${branch}/${component}/debian"
              echo "ARMHFTAGS=$edited_tags"
              ;;
            *amd64*)
              echo "CONTEXT=${branch}/debian"
              echo "AMD64TAGS=$edited_tags"
              ;;
            esac
          done
