name: Linux
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tags
        run: |
          set -x
          component=amd64
          for target in $(make echo-all-images); do
            case $target in
               *$component*)
                 ;;
               *)
                 continue
                 ;;
            esac
            branch=$(echo $target | cut -d'/' -f1)
            tags=$(echo $target | cut -d':' -f2-)
            tag1=$(echo $tags | cut -d',' -f1)
            tag2=$(echo $tags | cut -d',' -f2)
            tag3=$(echo $tags | cut -d',' -f3)
            echo "CONTEXT=${branch}/debian"
            echo "AMD64TAGS=${{ env.REPOSITORY }}:${tag1},${{ env.REPOSITORY }}:${tag2},${{ env.REPOSITORY }}:${tag3}"
          done
      - name: Setup tags 2
        run: |
          set -x
          component=amd64
          for target in $(make echo-all-images); do
            case $target in
               *$component*)
                 ;;
               *)
                 continue
                 ;;
            esac
            branch=$(echo $target | cut -d'/' -f1)
            tags=$(echo $target | cut -d':' -f2-)
            # replaced="$(echo $tags | tr , ' ')"
            # echo $replaced
            final_tag_array=()
            for tag in $(echo $tags | tr , ' '); do
              final_tag_array+="repo:${tag}"
            done
            final_tags_str="AMD64TAGS=$(IFS=,; echo "${final_tag_array[*]}")"
            echo $final_tags_str
          done
